
% Copyright 2016 The University of Texas at Austin
%
% For licensing information see
%                http://www.cs.utexas.edu/users/flame/license.html 
%                                                                                 
% Programmed by: Ernest Kirubakaran Selvaraj
%                ernest.kirubakaran@gmail.com

function [ Y_out ] = mvmult_n_unb_var1_unb( A, X, Y )

  [ AT, ...
    AB ] = FLA_Part_2x1( A, ...
                         0, 'FLA_TOP' );

  [ YT, ...
    YB ] = FLA_Part_2x1( Y, ...
                         0, 'FLA_TOP' );

  while ( size( AT, 1 ) < size( A, 1 ) )

    [ A0, ...
      a1t, ...
      A2 ] = FLA_Repart_2x1_to_3x1( AT, ...
                                    AB, ...
                                    1, 'FLA_BOTTOM' );

    [ Y0, ...
      y1t, ...
      Y2 ] = FLA_Repart_2x1_to_3x1( YT, ...
                                    YB, ...
                                    1, 'FLA_BOTTOM' );

    %------------------------------------------------------------%

    y1t = laff_dots (a1t, X, y1t)
    %------------------------------------------------------------%

    [ AT, ...
      AB ] = FLA_Cont_with_3x1_to_2x1( A0, ...
                                       a1t, ...
                                       A2, ...
                                       'FLA_TOP' );

    [ YT, ...
      YB ] = FLA_Cont_with_3x1_to_2x1( Y0, ...
                                       y1t, ...
                                       Y2, ...
                                       'FLA_TOP' );

  end

  Y_out = [ YT
            YB ];

return
